//! Markdown report builder.
//!
//! The output style follows the serde-hkx binary-format spec: every structure
//! gets a `Field | Description | Type | Size | Offset` table, byte layouts get
//! ASCII box diagrams, and real bytes are shown as hexdumps.

use std::fmt::Write as _;

use super::dist_path;

/// Column alignment for [`Doc::table`].
#[derive(Clone, Copy)]
pub enum Align {
    Left,
    Right,
    Center,
}

/// One bitfield of a register diagram: `(high_bit, low_bit, name)`.
pub type Field<'a> = (u32, u32, &'a str);

/// An in-memory Markdown document that is written to `core/tests/dist/<rel>`.
pub struct Doc {
    rel: String,
    out: String,
}

impl Doc {
    /// Starts a document with a `# title` and a provenance block naming the
    /// implementation file (`src`, relative to `core/src/`), the mirrored
    /// test file and the data source (real ROM / synthetic).
    pub fn new(rel: &str, title: &str, src: &str) -> Self {
        let mut doc = Doc { rel: rel.to_string(), out: String::new() };
        let _ = writeln!(doc.out, "# {title}\n");
        let _ = writeln!(
            doc.out,
            "> Generated by `cargo test -p nds-core` — test: [`core/tests/{src}`](../{up}{src}), \
             implementation: [`core/src/{src}`](../../{up}src/{src}).  \n\
             > Do not edit by hand; re-run the test instead.\n",
            up = "../".repeat(rel.matches('/').count()),
        );
        doc
    }

    /// Records where the analysed bytes came from.
    pub fn source(&mut self, label: &str) -> &mut Self {
        let _ = writeln!(self.out, "**Data source:** {label}\n");
        self
    }

    pub fn h2(&mut self, s: &str) -> &mut Self {
        let _ = writeln!(self.out, "## {s}\n");
        self
    }

    pub fn h3(&mut self, s: &str) -> &mut Self {
        let _ = writeln!(self.out, "### {s}\n");
        self
    }

    pub fn p(&mut self, s: &str) -> &mut Self {
        let _ = writeln!(self.out, "{s}\n");
        self
    }

    /// Bulleted list.
    pub fn bullets<S: AsRef<str>>(&mut self, items: &[S]) -> &mut Self {
        for i in items {
            let _ = writeln!(self.out, "- {}", i.as_ref());
        }
        self.out.push('\n');
        self
    }

    /// `> **Note** …` call-out.
    pub fn note(&mut self, s: &str) -> &mut Self {
        let _ = writeln!(self.out, "> [!NOTE]\n> {}\n", s.replace('\n', "\n> "));
        self
    }

    /// Fenced code block.
    pub fn code(&mut self, lang: &str, body: &str) -> &mut Self {
        let _ = writeln!(self.out, "```{lang}\n{}\n```\n", body.trim_end());
        self
    }

    /// Markdown table. Cells containing `|` are escaped.
    pub fn table<S: AsRef<str>>(
        &mut self,
        headers: &[(&str, Align)],
        rows: &[Vec<S>],
    ) -> &mut Self {
        let esc = |s: &str| s.replace('|', "\\|").replace('\n', "<br>");
        let mut widths: Vec<usize> = headers.iter().map(|(h, _)| h.len().max(3)).collect();
        for row in rows {
            for (w, c) in widths.iter_mut().zip(row) {
                *w = (*w).max(display_width(&esc(c.as_ref())));
            }
        }
        let pad = |s: &str, w: usize, a: Align| {
            let n = w.saturating_sub(display_width(s));
            match a {
                Align::Left => format!("{s}{}", " ".repeat(n)),
                Align::Right => format!("{}{s}", " ".repeat(n)),
                Align::Center => format!("{}{s}{}", " ".repeat(n / 2), " ".repeat(n - n / 2)),
            }
        };
        let mut line = String::from("|");
        for ((h, a), w) in headers.iter().zip(&widths) {
            let _ = write!(line, " {} |", pad(h, *w, *a));
        }
        let _ = writeln!(self.out, "{line}");
        let mut line = String::from("|");
        for ((_, a), w) in headers.iter().zip(&widths) {
            let dashes = "-".repeat(w.saturating_sub(1));
            let cell = match a {
                Align::Left => format!("{dashes}-"),
                Align::Right => format!("{dashes}:"),
                Align::Center => format!(":{}:", "-".repeat(w.saturating_sub(2))),
            };
            let _ = write!(line, " {cell} |");
        }
        let _ = writeln!(self.out, "{line}");
        for row in rows {
            let mut line = String::from("|");
            for (i, (_, a)) in headers.iter().enumerate() {
                let c = row.get(i).map(|c| esc(c.as_ref())).unwrap_or_default();
                let _ = write!(line, " {} |", pad(&c, widths[i], *a));
            }
            let _ = writeln!(self.out, "{line}");
        }
        self.out.push('\n');
        self
    }

    /// Classic 16-bytes-per-line hexdump with an ASCII gutter.
    pub fn hexdump(&mut self, base: u64, bytes: &[u8]) -> &mut Self {
        let body = hexdump(base, bytes);
        self.code("text", &body)
    }

    /// Register diagram. Fields must be given MSB→LSB and may leave gaps
    /// (gaps are drawn as `-`).
    pub fn bitfield(&mut self, title: &str, bits: u32, fields: &[Field]) -> &mut Self {
        let body = bitfield_diagram(title, bits, fields);
        self.code("text", &body)
    }

    /// Embeds an image written next to this document.
    pub fn image(&mut self, alt: &str, file_name: &str) -> &mut Self {
        let _ = writeln!(self.out, "![{alt}]({file_name})\n");
        self
    }

    /// Appends raw Markdown.
    pub fn raw(&mut self, s: &str) -> &mut Self {
        self.out.push_str(s);
        self
    }

    /// Writes the document to `core/tests/dist/<rel>`.
    pub fn save(&self) {
        std::fs::write(dist_path(&self.rel), &self.out).unwrap();
    }
}

/// Width in terminal columns, counting CJK as 2 so tables stay aligned in a
/// monospace editor view.
fn display_width(s: &str) -> usize {
    s.chars().map(|c| if (c as u32) >= 0x1100 { 2 } else { 1 }).sum()
}

pub fn hexdump(base: u64, bytes: &[u8]) -> String {
    let mut out =
        String::from("Offset    00 01 02 03 04 05 06 07  08 09 0A 0B 0C 0D 0E 0F  ASCII\n");
    for (i, chunk) in bytes.chunks(16).enumerate() {
        let _ = write!(out, "{:08X}  ", base + i as u64 * 16);
        for j in 0..16 {
            match chunk.get(j) {
                Some(b) => {
                    let _ = write!(out, "{b:02X} ");
                }
                None => out.push_str("   "),
            }
            if j == 7 {
                out.push(' ');
            }
        }
        let _ = writeln!(out, " {}", super::ascii(chunk));
    }
    out
}

/// Draws a register as a row of labelled boxes:
///
/// ```text
///  15   14-13  12-8     7-0
/// +---+-------+------+--------+
/// | E |  MODE |  -   | VALUE  |
/// +---+-------+------+--------+
/// ```
pub fn bitfield_diagram(title: &str, bits: u32, fields: &[Field]) -> String {
    // Fill gaps with "-" fields so the diagram always covers every bit.
    let mut all: Vec<(u32, u32, String)> = Vec::new();
    let mut next_hi = bits as i64 - 1;
    for &(hi, lo, name) in fields {
        if (hi as i64) < next_hi {
            all.push((next_hi as u32, hi + 1, "-".into()));
        }
        all.push((hi, lo, name.to_string()));
        next_hi = lo as i64 - 1;
    }
    if next_hi >= 0 {
        all.push((next_hi as u32, 0, "-".into()));
    }
    let labels: Vec<String> = all
        .iter()
        .map(|(hi, lo, _)| if hi == lo { format!("{hi}") } else { format!("{hi}-{lo}") })
        .collect();
    let widths: Vec<usize> =
        all.iter().zip(&labels).map(|((_, _, n), l)| display_width(n).max(l.len()) + 2).collect();
    let mut top = String::new();
    let mut border = String::from("+");
    let mut names = String::from("|");
    for (((_, _, n), l), w) in all.iter().zip(&labels).zip(&widths) {
        let _ = write!(top, " {l:^w$}", w = *w);
        border.push_str(&"-".repeat(*w));
        border.push('+');
        let pad = w - display_width(n);
        let _ = write!(names, "{}{n}{}|", " ".repeat(pad / 2), " ".repeat(pad - pad / 2));
    }
    format!("{title}\n{top}\n{border}\n{names}\n{border}")
}

/// `0x1234ABCD` style hex with a fixed width.
pub fn hx(v: u64, digits: usize) -> String {
    format!("0x{v:0digits$X}")
}

/// Human byte size (`32 KiB`, `4 MiB`, `123 B`).
pub fn size(n: u64) -> String {
    if n >= 1 << 20 && n.is_multiple_of(1 << 20) {
        format!("{} MiB", n >> 20)
    } else if n >= 1 << 10 && n.is_multiple_of(1 << 10) {
        format!("{} KiB", n >> 10)
    } else {
        format!("{n} B")
    }
}

/// Left-aligned column shorthand.
pub const L: Align = Align::Left;
/// Right-aligned column shorthand.
pub const R: Align = Align::Right;
/// Centered column shorthand.
pub const C: Align = Align::Center;
