[package]
edition = "2021"
name = "lunaris"
version = "2.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
winres = "0.1.12" # Meta information can be added to the exe.

[dependencies]
gl = "0.14.0"
glfw = "0.62.0"
imgui = "0.7.0"
imgui-opengl-renderer = "0.11.0"
nds-core = {path = "../core"}
rfd = "0.14"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"

[profile.release]
debug = true
