//! The **Config** menu: the settings dialogs, and the switches beside them.

use egui::Ui;

use super::{Action, Picked, Unavailable, unavailable};
use crate::{
    app::{MelonEgui, Pane},
    i18n::I18nKey as K,
};

pub(super) fn config_menu(app: &mut MelonEgui, ui: &mut Ui) -> Option<Action> {
    let mut m = Picked::default();
    ui.menu_button(app.i18n().s(K::ConfigLabel), |ui| {
        m.pane(app, ui, true, K::EmuSettings, Pane::EmuSettings);
        m.pane(app, ui, true, K::Preferences, Pane::Preferences);
        ui.separator();

        m.pane(app, ui, true, K::InputAndHotkeys, Pane::Input);
        m.pane(app, ui, true, K::VideoSettings, Pane::VideoSettings);
        unavailable(app, ui, K::CameraSettings, Unavailable::Bindings);
        m.pane(app, ui, true, K::AudioSettings, Pane::AudioSettings);
        m.pane(app, ui, true, K::MultiplayerSettings, Pane::Wireless);
        m.pane(app, ui, true, K::WifiSettings, Pane::Wireless);
        // The firmware is generated by the shim; its contents are not settable.
        unavailable(app, ui, K::FirmwareSettings, Unavailable::Bindings);
        m.pane(app, ui, true, K::InterfaceSettings, Pane::Interface);
        m.pane(app, ui, true, K::PathSettings, Pane::Paths);
        ui.separator();

        let (limit, sync) = (app.i18n().s(K::LimitFramerate), app.i18n().s(K::AudioSync));
        ui.checkbox(&mut app.limit_framerate, limit);
        let has_audio = app.has_audio();
        ui.add_enabled(has_audio, egui::Checkbox::new(&mut app.audio_sync, sync))
            .on_disabled_hover_text(app.i18n().t(K::NoAudioDevice));
    });
    m.0
}
