//! The **Config** menu: the settings dialogs, and the switches beside them.

use egui::Ui;

use super::{Action, Unavailable, item, unavailable};
use crate::{
    app::{MelonEgui, Pane},
    i18n::I18nKey as K,
};

pub(super) fn config_menu(app: &mut MelonEgui, ui: &mut Ui) -> Option<Action> {
    let mut action = None;
    ui.menu_button(app.i18n().s(K::ConfigLabel), |ui| {
        for (key, pane) in
            [(K::EmuSettings, Pane::EmuSettings), (K::Preferences, Pane::Preferences)]
        {
            action = action.take().or_else(|| item(app, ui, true, key, Action::TogglePane(pane)));
        }
        ui.separator();

        action = action
            .take()
            .or_else(|| item(app, ui, true, K::InputAndHotkeys, Action::TogglePane(Pane::Input)));
        action = action.take().or_else(|| {
            item(app, ui, true, K::VideoSettings, Action::TogglePane(Pane::VideoSettings))
        });
        // No camera in the FFI.
        unavailable(app, ui, K::CameraSettings, Unavailable::Bindings);
        action = action.take().or_else(|| {
            item(app, ui, true, K::AudioSettings, Action::TogglePane(Pane::AudioSettings))
        });
        action = action.take().or_else(|| {
            item(app, ui, true, K::MultiplayerSettings, Action::TogglePane(Pane::Wireless))
        });
        action = action
            .take()
            .or_else(|| item(app, ui, true, K::WifiSettings, Action::TogglePane(Pane::Wireless)));
        // The firmware is generated by the shim; its contents are not settable.
        unavailable(app, ui, K::FirmwareSettings, Unavailable::Bindings);
        action = action.take().or_else(|| {
            item(app, ui, true, K::InterfaceSettings, Action::TogglePane(Pane::Interface))
        });
        action = action
            .take()
            .or_else(|| item(app, ui, true, K::PathSettings, Action::TogglePane(Pane::Paths)));
        ui.separator();

        let (limit, sync) = (app.i18n().s(K::LimitFramerate), app.i18n().s(K::AudioSync));
        ui.checkbox(&mut app.limit_framerate, limit);
        let has_audio = app.has_audio();
        ui.add_enabled(has_audio, egui::Checkbox::new(&mut app.audio_sync, sync))
            .on_disabled_hover_text("No audio output device.");
    });
    action
}
